#!/usr/bin/env python3
"""
Generate comprehensive CET-4 vocabulary-bank.json
Uses compact word data + template-based example generation to fit ~2000+ words.
"""

import json, os, random

# ============================================================
# Word database: (word, pronunciation, chinese_def, category, difficulty)
# Categories: verb, noun, adjective, adverb, phrase
# Difficulty: 1-5
# ============================================================

WORDS = [
    # ── Verbs (动词) ─────────────────────────────────
    ("abandon", "/əˈbændən/", "v. 放弃；抛弃；遗弃", "verb", 2),
    ("absorb", "/əbˈzɔːrb/", "v. 吸收；吸引；理解", "verb", 2),
    ("abuse", "/əˈbjuːz/", "v. 滥用；虐待；辱骂", "verb", 3),
    ("accelerate", "/əkˈseləreɪt/", "v. 加速；促进", "verb", 3),
    ("accompany", "/əˈkʌmpəni/", "v. 陪伴；伴随；为…伴奏", "verb", 2),
    ("accomplish", "/əˈkɑːmplɪʃ/", "v. 完成；实现；达到", "verb", 2),
    ("accumulate", "/əˈkjuːmjəleɪt/", "v. 积累；积聚；堆积", "verb", 3),
    ("accuse", "/əˈkjuːz/", "v. 指控；指责；谴责", "verb", 2),
    ("achieve", "/əˈtʃiːv/", "v. 实现；达到；获得", "verb", 1),
    ("acknowledge", "/əkˈnɑːlɪdʒ/", "v. 承认；确认；致谢", "verb", 3),
    ("acquire", "/əˈkwaɪər/", "v. 获得；习得；收购", "verb", 2),
    ("adapt", "/əˈdæpt/", "v. 适应；改编；调整", "verb", 2),
    ("address", "/əˈdres/", "v. 处理；演讲；称呼", "verb", 2),
    ("adjust", "/əˈdʒʌst/", "v. 调整；适应；校准", "verb", 2),
    ("admire", "/ədˈmaɪər/", "v. 钦佩；赞赏；欣赏", "verb", 1),
    ("admit", "/ədˈmɪt/", "v. 承认；准许进入；容纳", "verb", 1),
    ("adopt", "/əˈdɑːpt/", "v. 采用；采纳；收养", "verb", 2),
    ("advance", "/ədˈvæns/", "v. 前进；推进；提出", "verb", 2),
    ("advocate", "/ˈædvəkeɪt/", "v. 提倡；拥护；主张", "verb", 3),
    ("affect", "/əˈfekt/", "v. 影响；感动；假装", "verb", 2),
    ("afford", "/əˈfɔːrd/", "v. 负担得起；提供；给予", "verb", 1),
    ("allocate", "/ˈæləkeɪt/", "v. 分配；拨出", "verb", 3),
    ("alter", "/ˈɔːltər/", "v. 改变；修改", "verb", 2),
    ("analyze", "/ˈænəlaɪz/", "v. 分析；解析", "verb", 2),
    ("announce", "/əˈnaʊns/", "v. 宣布；通告；播报", "verb", 2),
    ("anticipate", "/ænˈtɪsɪpeɪt/", "v. 预期；期望；预见", "verb", 3),
    ("apologize", "/əˈpɑːlədʒaɪz/", "v. 道歉；认错", "verb", 1),
    ("appeal", "/əˈpiːl/", "v. 吸引；呼吁；上诉", "verb", 3),
    ("apply", "/əˈplaɪ/", "v. 申请；应用；适用", "verb", 1),
    ("appreciate", "/əˈpriːʃieɪt/", "v. 欣赏；感激；领会", "verb", 2),
    ("approach", "/əˈproʊtʃ/", "v. 接近；着手处理", "verb", 2),
    ("approve", "/əˈpruːv/", "v. 批准；赞成；认可", "verb", 2),
    ("argue", "/ˈɑːrɡjuː/", "v. 争论；辩论；主张", "verb", 1),
    ("arise", "/əˈraɪz/", "v. 出现；产生；起床", "verb", 3),
    ("arrange", "/əˈreɪndʒ/", "v. 安排；整理；筹备", "verb", 1),
    ("arrest", "/əˈrest/", "v. 逮捕；阻止；吸引", "verb", 2),
    ("assess", "/əˈses/", "v. 评估；评定；估价", "verb", 2),
    ("assign", "/əˈsaɪn/", "v. 分配；指派；指定", "verb", 2),
    ("assist", "/əˈsɪst/", "v. 帮助；协助；援助", "verb", 2),
    ("assume", "/əˈsuːm/", "v. 假设；假定；承担", "verb", 2),
    ("assure", "/əˈʃʊr/", "v. 保证；使确信；担保", "verb", 3),
    ("attach", "/əˈtætʃ/", "v. 附上；连接；使依恋", "verb", 2),
    ("attain", "/əˈteɪn/", "v. 达到；获得；实现", "verb", 3),
    ("attempt", "/əˈtempt/", "v. 尝试；企图；试图", "verb", 2),
    ("attend", "/əˈtend/", "v. 参加；出席；照料", "verb", 1),
    ("attract", "/əˈtrækt/", "v. 吸引；引起；招引", "verb", 2),
    ("attribute", "/əˈtrɪbjuːt/", "v. 把…归因于", "verb", 3),
    ("avoid", "/əˈvɔɪd/", "v. 避免；回避；躲开", "verb", 1),
    ("ban", "/bæn/", "v. 禁止；取缔", "verb", 2),
    ("bargain", "/ˈbɑːrɡən/", "v. 讨价还价；谈判", "verb", 3),
    ("bear", "/ber/", "v. 忍受；承担；生育", "verb", 2),
    ("beg", "/beɡ/", "v. 乞求；恳求；乞讨", "verb", 2),
    ("behave", "/bɪˈheɪv/", "v. 行为；表现；举止", "verb", 1),
    ("benefit", "/ˈbenɪfɪt/", "v. 受益；对…有益", "verb", 2),
    ("blame", "/bleɪm/", "v. 责备；归咎于", "verb", 1),
    ("boast", "/boʊst/", "v. 吹嘘；夸耀；以…为豪", "verb", 3),
    ("boom", "/buːm/", "v. 繁荣；迅速发展；轰鸣", "verb", 3),
    ("bother", "/ˈbɑːðər/", "v. 打扰；烦恼；费心", "verb", 2),
    ("breed", "/briːd/", "v. 繁殖；培育；导致", "verb", 3),
    ("broadcast", "/ˈbrɔːdkæst/", "v. 广播；播送；散布", "verb", 2),
    ("calculate", "/ˈkælkjuleɪt/", "v. 计算；估计；计划", "verb", 2),
    ("cancel", "/ˈkænsl/", "v. 取消；撤销；废除", "verb", 1),
    ("capture", "/ˈkæptʃər/", "v. 捕获；俘获；引起", "verb", 2),
    ("celebrate", "/ˈselɪbreɪt/", "v. 庆祝；赞美；举行", "verb", 1),
    ("challenge", "/ˈtʃælɪndʒ/", "v. 挑战；质疑", "verb", 2),
    ("characterize", "/ˈkærəktəraɪz/", "v. 以…为特征；描绘", "verb", 4),
    ("chase", "/tʃeɪs/", "v. 追逐；追赶；追求", "verb", 2),
    ("cheat", "/tʃiːt/", "v. 欺骗；作弊；欺诈", "verb", 2),
    ("claim", "/kleɪm/", "v. 声称；要求；认领", "verb", 2),
    ("clarify", "/ˈklærɪfaɪ/", "v. 澄清；阐明；使明确", "verb", 2),
    ("classify", "/ˈklæsɪfaɪ/", "v. 分类；归类；分等级", "verb", 3),
    ("collapse", "/kəˈlæps/", "v. 倒塌；崩溃；暴跌", "verb", 3),
    ("combine", "/kəmˈbaɪn/", "v. 结合；联合；合并", "verb", 2),
    ("commit", "/kəˈmɪt/", "v. 承诺；犯（罪）；投入", "verb", 3),
    ("communicate", "/kəˈmjuːnɪkeɪt/", "v. 交流；沟通；传达", "verb", 2),
    ("compare", "/kəmˈper/", "v. 比较；对比；比喻", "verb", 1),
    ("compensate", "/ˈkɑːmpenseɪt/", "v. 补偿；赔偿；弥补", "verb", 3),
    ("compete", "/kəmˈpiːt/", "v. 竞争；比赛；对抗", "verb", 2),
    ("complain", "/kəmˈpleɪn/", "v. 抱怨；投诉；诉说", "verb", 2),
    ("complicate", "/ˈkɑːmplɪkeɪt/", "v. 使复杂化；使难懂", "verb", 3),
    ("compose", "/kəmˈpoʊz/", "v. 组成；创作；作曲", "verb", 3),
    ("concentrate", "/ˈkɑːnsntreɪt/", "v. 集中；专心；浓缩", "verb", 2),
    ("conclude", "/kənˈkluːd/", "v. 结束；得出结论；推断", "verb", 2),
    ("conduct", "/kənˈdʌkt/", "v. 进行；实施；指挥", "verb", 2),
    ("confirm", "/kənˈfɜːrm/", "v. 确认；证实；批准", "verb", 2),
    ("confront", "/kənˈfrʌnt/", "v. 面对；正视；对抗", "verb", 3),
    ("confuse", "/kənˈfjuːz/", "v. 使困惑；混淆；搞乱", "verb", 2),
    ("connect", "/kəˈnekt/", "v. 连接；联系；关联", "verb", 1),
    ("conquer", "/ˈkɑːŋkər/", "v. 征服；克服；战胜", "verb", 3),
    ("consist", "/kənˈsɪst/", "v. 由…组成；在于；符合", "verb", 2),
    ("construct", "/kənˈstrʌkt/", "v. 建造；构建；创立", "verb", 2),
    ("consult", "/kənˈsʌlt/", "v. 咨询；查阅；商量", "verb", 2),
    ("consume", "/kənˈsuːm/", "v. 消耗；消费；吃；喝", "verb", 2),
    ("contain", "/kənˈteɪn/", "v. 包含；容纳；控制", "verb", 1),
    ("contribute", "/kənˈtrɪbjuːt/", "v. 贡献；捐献；投稿", "verb", 2),
    ("convey", "/kənˈveɪ/", "v. 传达；表达；运送", "verb", 3),
    ("convince", "/kənˈvɪns/", "v. 说服；使确信；使信服", "verb", 2),
    ("cooperate", "/koʊˈɑːpəreɪt/", "v. 合作；协作；配合", "verb", 2),
    ("cope", "/koʊp/", "v. 应对；处理；对付", "verb", 2),
    ("correspond", "/ˌkɔːrəˈspɑːnd/", "v. 相符；对应；通信", "verb", 3),
    ("create", "/kriˈeɪt/", "v. 创造；创建；引起", "verb", 1),
    ("cultivate", "/ˈkʌltɪveɪt/", "v. 培养；耕作；建立", "verb", 3),
    ("cure", "/kjʊr/", "v. 治愈；治疗；解决", "verb", 2),
    ("debate", "/dɪˈbeɪt/", "v. 辩论；争论；讨论", "verb", 2),
    ("deceive", "/dɪˈsiːv/", "v. 欺骗；蒙蔽；误导", "verb", 3),
    ("declare", "/dɪˈkler/", "v. 宣布；声明；宣告", "verb", 2),
    ("decline", "/dɪˈklaɪn/", "v. 下降；拒绝；衰落", "verb", 3),
    ("decorate", "/ˈdekəreɪt/", "v. 装饰；装潢；授勋", "verb", 2),
    ("decrease", "/dɪˈkriːs/", "v. 减少；降低；减小", "verb", 2),
    ("defeat", "/dɪˈfiːt/", "v. 击败；战胜；挫败", "verb", 2),
    ("defend", "/dɪˈfend/", "v. 防御；保卫；辩护", "verb", 2),
    ("define", "/dɪˈfaɪn/", "v. 定义；界定；明确", "verb", 2),
    ("delay", "/dɪˈleɪ/", "v. 延迟；推迟；耽搁", "verb", 2),
    ("deliver", "/dɪˈlɪvər/", "v. 递送；发表；接生", "verb", 2),
    ("demonstrate", "/ˈdemənstreɪt/", "v. 展示；证明；示威", "verb", 3),
    ("deny", "/dɪˈnaɪ/", "v. 否认；拒绝承认；拒绝给予", "verb", 2),
    ("depart", "/dɪˈpɑːrt/", "v. 离开；出发；偏离", "verb", 3),
    ("depend", "/dɪˈpend/", "v. 依赖；取决于；信赖", "verb", 1),
    ("deposit", "/dɪˈpɑːzɪt/", "v. 存放；储蓄；使沉积", "verb", 3),
    ("depress", "/dɪˈpres/", "v. 使沮丧；使萧条；压低", "verb", 3),
    ("derive", "/dɪˈraɪv/", "v. 来源于；获得；导出", "verb", 3),
    ("describe", "/dɪˈskraɪb/", "v. 描述；形容；描绘", "verb", 1),
    ("deserve", "/dɪˈzɜːrv/", "v. 值得；应得；应受", "verb", 2),
    ("desire", "/dɪˈzaɪər/", "v. 渴望；想要；期望", "verb", 2),
    ("destroy", "/dɪˈstrɔɪ/", "v. 破坏；毁灭；消灭", "verb", 2),
    ("detect", "/dɪˈtekt/", "v. 发现；察觉；探测", "verb", 2),
    ("determine", "/dɪˈtɜːrmɪn/", "v. 决定；确定；下决心", "verb", 2),
    ("devote", "/dɪˈvoʊt/", "v. 致力于；奉献；投入", "verb", 2),
    ("disappear", "/ˌdɪsəˈpɪr/", "v. 消失；失踪；不复存在", "verb", 2),
    ("discipline", "/ˈdɪsəplɪn/", "v. 训练；管教；惩罚", "verb", 3),
    ("discourage", "/dɪsˈkɜːrɪdʒ/", "v. 劝阻；使气馁；阻碍", "verb", 3),
    ("dismiss", "/dɪsˈmɪs/", "v. 解雇；驳回；不予考虑", "verb", 3),
    ("display", "/dɪˈspleɪ/", "v. 展示；显示；陈列", "verb", 2),
    ("dispose", "/dɪˈspoʊz/", "v. 处理；处置；安排", "verb", 3),
    ("dispute", "/dɪˈspjuːt/", "v. 争论；质疑；争夺", "verb", 3),
    ("dissolve", "/dɪˈzɑːlv/", "v. 溶解；解散；消失", "verb", 3),
    ("distinguish", "/dɪˈstɪŋɡwɪʃ/", "v. 区分；辨别；使出众", "verb", 3),
    ("distribute", "/dɪˈstrɪbjuːt/", "v. 分配；分发；散布", "verb", 2),
    ("disturb", "/dɪˈstɜːrb/", "v. 打扰；扰乱；使不安", "verb", 2),
    ("dominate", "/ˈdɑːmɪneɪt/", "v. 支配；主导；占优势", "verb", 3),
    ("donate", "/ˈdoʊneɪt/", "v. 捐赠；捐献；赠送", "verb", 2),
    ("draft", "/dræft/", "v. 起草；草拟；征召", "verb", 3),
    ("drag", "/dræɡ/", "v. 拖；拉；拽", "verb", 2),
    ("drain", "/dreɪn/", "v. 排空；耗尽；流干", "verb", 3),
    ("earn", "/ɜːrn/", "v. 赚取；挣得；获得", "verb", 1),
    ("ease", "/iːz/", "v. 缓解；减轻；放松", "verb", 2),
    ("educate", "/ˈedʒukeɪt/", "v. 教育；培养；训练", "verb", 2),
    ("eliminate", "/ɪˈlɪmɪneɪt/", "v. 消除；淘汰；排除", "verb", 3),
    ("embrace", "/ɪmˈbreɪs/", "v. 拥抱；接受；包含", "verb", 3),
    ("emerge", "/ɪˈmɜːrdʒ/", "v. 出现；浮现；显露", "verb", 3),
    ("emit", "/ɪˈmɪt/", "v. 发出；排放；散发", "verb", 3),
    ("emphasize", "/ˈemfəsaɪz/", "v. 强调；着重；使突出", "verb", 2),
    ("employ", "/ɪmˈplɔɪ/", "v. 雇用；使用；采用", "verb", 2),
    ("enable", "/ɪˈneɪbl/", "v. 使能够；使成为可能", "verb", 2),
    ("encounter", "/ɪnˈkaʊntər/", "v. 遇到；遭遇；偶遇", "verb", 2),
    ("encourage", "/ɪnˈkɜːrɪdʒ/", "v. 鼓励；激励；促进", "verb", 1),
    ("engage", "/ɪnˈɡeɪdʒ/", "v. 从事；参与；吸引", "verb", 3),
    ("enhance", "/ɪnˈhæns/", "v. 增强；提高；改善", "verb", 3),
    ("enrich", "/ɪnˈrɪtʃ/", "v. 充实；使丰富；使富裕", "verb", 3),
    ("ensure", "/ɪnˈʃʊr/", "v. 确保；保证；使安全", "verb", 2),
    ("entertain", "/ˌentərˈteɪn/", "v. 娱乐；招待；考虑", "verb", 2),
    ("establish", "/ɪˈstæblɪʃ/", "v. 建立；创立；确定", "verb", 2),
    ("estimate", "/ˈestɪmeɪt/", "v. 估计；估算；评价", "verb", 2),
    ("evaluate", "/ɪˈvæljueɪt/", "v. 评价；评估；估值", "verb", 2),
    ("evolve", "/ɪˈvɑːlv/", "v. 进化；发展；逐步形成", "verb", 3),
    ("exaggerate", "/ɪɡˈzædʒəreɪt/", "v. 夸张；夸大；言过其实", "verb", 3),
    ("examine", "/ɪɡˈzæmɪn/", "v. 检查；审查；考试", "verb", 2),
    ("exceed", "/ɪkˈsiːd/", "v. 超过；超越；胜过", "verb", 2),
    ("exchange", "/ɪksˈtʃeɪndʒ/", "v. 交换；兑换；交流", "verb", 2),
    ("exclude", "/ɪkˈskluːd/", "v. 排除；排斥；不包括", "verb", 3),
    ("execute", "/ˈeksɪkjuːt/", "v. 执行；实施；处决", "verb", 3),
    ("exhibit", "/ɪɡˈzɪbɪt/", "v. 展出；表现；显示", "verb", 3),
    ("expand", "/ɪkˈspænd/", "v. 扩张；扩展；膨胀", "verb", 2),
    ("exploit", "/ɪkˈsplɔɪt/", "v. 利用；开发；剥削", "verb", 3),
    ("explore", "/ɪkˈsplɔːr/", "v. 探索；探究；考察", "verb", 2),
    ("export", "/ɪkˈspɔːrt/", "v. 出口；输出；传播", "verb", 2),
    ("expose", "/ɪkˈspoʊz/", "v. 暴露；揭露；使接触", "verb", 3),
    ("extend", "/ɪkˈstend/", "v. 延伸；扩展；给予", "verb", 2),
    ("facilitate", "/fəˈsɪlɪteɪt/", "v. 促进；使容易；帮助", "verb", 4),
    ("fade", "/feɪd/", "v. 褪色；逐渐消失；衰落", "verb", 2),
    ("fasten", "/ˈfæsn/", "v. 系紧；扣紧；固定", "verb", 2),
    ("finance", "/ˈfaɪnæns/", "v. 资助；提供资金", "verb", 3),
    ("flourish", "/ˈflɜːrɪʃ/", "v. 繁荣；兴旺；茂盛", "verb", 3),
    ("forbid", "/fərˈbɪd/", "v. 禁止；阻止；妨碍", "verb", 2),
    ("forecast", "/ˈfɔːrkæst/", "v. 预测；预报；预示", "verb", 3),
    ("fulfill", "/fʊlˈfɪl/", "v. 履行；实现；满足", "verb", 2),
    ("generate", "/ˈdʒenəreɪt/", "v. 产生；生成；引起", "verb", 2),
    ("govern", "/ˈɡʌvərn/", "v. 统治；管理；支配", "verb", 3),
    ("grasp", "/ɡræsp/", "v. 抓住；理解；掌握", "verb", 2),
    ("guarantee", "/ˌɡærənˈtiː/", "v. 保证；担保", "verb", 2),
    ("handle", "/ˈhændl/", "v. 处理；操作；应对", "verb", 2),
    ("hesitate", "/ˈhezɪteɪt/", "v. 犹豫；迟疑；顾虑", "verb", 2),
    ("highlight", "/ˈhaɪlaɪt/", "v. 突出；强调；使显著", "verb", 2),
    ("identify", "/aɪˈdentɪfaɪ/", "v. 识别；确认；认定", "verb", 2),
    ("ignore", "/ɪɡˈnɔːr/", "v. 忽视；忽略；不理睬", "verb", 2),
    ("illustrate", "/ˈɪləstreɪt/", "v. 说明；阐明；加插图", "verb", 2),
    ("imitate", "/ˈɪmɪteɪt/", "v. 模仿；仿效；模拟", "verb", 2),
    ("implement", "/ˈɪmplɪment/", "v. 实施；执行；贯彻", "verb", 3),
    ("imply", "/ɪmˈplaɪ/", "v. 暗示；意味；隐含", "verb", 2),
    ("import", "/ɪmˈpɔːrt/", "v. 进口；输入；引进", "verb", 2),
    ("impose", "/ɪmˈpoʊz/", "v. 强加；征收；强迫", "verb", 3),
    ("impress", "/ɪmˈpres/", "v. 给…留下印象；使钦佩", "verb", 2),
    ("indicate", "/ˈɪndɪkeɪt/", "v. 表明；指示；显示", "verb", 2),
    ("infect", "/ɪnˈfekt/", "v. 感染；传染；影响", "verb", 3),
    ("inherit", "/ɪnˈherɪt/", "v. 继承；遗传；接手", "verb", 3),
    ("inquire", "/ɪnˈkwaɪər/", "v. 询问；打听；调查", "verb", 3),
    ("insert", "/ɪnˈsɜːrt/", "v. 插入；嵌入；添加", "verb", 2),
    ("inspect", "/ɪnˈspekt/", "v. 检查；视察；检阅", "verb", 3),
    ("inspire", "/ɪnˈspaɪər/", "v. 激励；启发；鼓舞", "verb", 2),
    ("install", "/ɪnˈstɔːl/", "v. 安装；设置；任命", "verb", 2),
    ("integrate", "/ˈɪntɪɡreɪt/", "v. 整合；融合；使一体化", "verb", 3),
    ("intend", "/ɪnˈtend/", "v. 打算；计划；意指", "verb", 2),
    ("interpret", "/ɪnˈtɜːrprɪt/", "v. 解释；口译；理解", "verb", 3),
    ("interrupt", "/ˌɪntəˈrʌpt/", "v. 打断；中断；插嘴", "verb", 2),
    ("invest", "/ɪnˈvest/", "v. 投资；投入；授予", "verb", 3),
    ("investigate", "/ɪnˈvestɪɡeɪt/", "v. 调查；研究；审查", "verb", 2),
    ("involve", "/ɪnˈvɑːlv/", "v. 涉及；包含；使参与", "verb", 2),
    ("isolate", "/ˈaɪsəleɪt/", "v. 隔离；孤立；分离", "verb", 3),
    ("justify", "/ˈdʒʌstɪfaɪ/", "v. 为…辩护；证明正当", "verb", 3),
    ("launch", "/lɔːntʃ/", "v. 发射；启动；推出", "verb", 2),
    ("liberate", "/ˈlɪbəreɪt/", "v. 解放；释放；使自由", "verb", 3),
    ("maintain", "/meɪnˈteɪn/", "v. 维持；保持；维修；主张", "verb", 2),
    ("manufacture", "/ˌmænjuˈfæktʃər/", "v. 制造；生产", "verb", 2),
    ("migrate", "/ˈmaɪɡreɪt/", "v. 迁移；迁徙；移动", "verb", 3),
    ("mislead", "/ˌmɪsˈliːd/", "v. 误导；引入歧途", "verb", 3),
    ("monitor", "/ˈmɑːnɪtər/", "v. 监视；监测；监控", "verb", 2),
    ("motivate", "/ˈmoʊtɪveɪt/", "v. 激励；激发；使有动机", "verb", 2),
    ("negotiate", "/nɪˈɡoʊʃieɪt/", "v. 谈判；协商；议定", "verb", 3),
    ("notify", "/ˈnoʊtɪfaɪ/", "v. 通知；告知；报告", "verb", 2),
    ("nourish", "/ˈnɜːrɪʃ/", "v. 滋养；养育；培养", "verb", 3),
    ("object", "/əbˈdʒekt/", "v. 反对；拒绝；抗议", "verb", 2),
    ("observe", "/əbˈzɜːrv/", "v. 观察；遵守；注意到", "verb", 2),
    ("obtain", "/əbˈteɪn/", "v. 获得；得到；存在", "verb", 2),
    ("occupy", "/ˈɑːkjupaɪ/", "v. 占据；占用；使忙碌", "verb", 2),
    ("offend", "/əˈfend/", "v. 冒犯；得罪；违反", "verb", 3),
    ("operate", "/ˈɑːpəreɪt/", "v. 操作；经营；动手术", "verb", 2),
    ("oppose", "/əˈpoʊz/", "v. 反对；对抗；抵制", "verb", 2),
    ("organize", "/ˈɔːrɡənaɪz/", "v. 组织；安排；整理", "verb", 1),
    ("overcome", "/ˌoʊvərˈkʌm/", "v. 克服；战胜；征服", "verb", 2),
    ("overlook", "/ˌoʊvərˈlʊk/", "v. 俯瞰；忽略；宽恕", "verb", 3),
    ("participate", "/pɑːrˈtɪsɪpeɪt/", "v. 参与；参加；分享", "verb", 2),
    ("perceive", "/pərˈsiːv/", "v. 感知；察觉；理解", "verb", 3),
    ("perform", "/pərˈfɔːrm/", "v. 执行；表演；表现", "verb", 2),
    ("permit", "/pərˈmɪt/", "v. 允许；许可；准许", "verb", 2),
    ("persist", "/pərˈsɪst/", "v. 坚持；持续；固执", "verb", 3),
    ("persuade", "/pərˈsweɪd/", "v. 说服；劝说；使相信", "verb", 2),
    ("possess", "/pəˈzes/", "v. 拥有；具有；控制", "verb", 2),
    ("postpone", "/poʊstˈpoʊn/", "v. 推迟；延期；延缓", "verb", 2),
    ("pray", "/preɪ/", "v. 祈祷；祷告；恳求", "verb", 2),
    ("predict", "/prɪˈdɪkt/", "v. 预测；预言；预报", "verb", 2),
    ("prescribe", "/prɪˈskraɪb/", "v. 开处方；规定；指示", "verb", 3),
    ("preserve", "/prɪˈzɜːrv/", "v. 保存；保护；维护", "verb", 3),
    ("prevail", "/prɪˈveɪl/", "v. 盛行；占优势；获胜", "verb", 3),
    ("proceed", "/prəˈsiːd/", "v. 继续；进行；前进", "verb", 3),
    ("prohibit", "/prəˈhɪbɪt/", "v. 禁止；阻止；妨碍", "verb", 3),
    ("promote", "/prəˈmoʊt/", "v. 促进；提升；推销", "verb", 2),
    ("propose", "/prəˈpoʊz/", "v. 提议；建议；求婚", "verb", 2),
    ("protest", "/prəˈtest/", "v. 抗议；反对；申辩", "verb", 3),
    ("publish", "/ˈpʌblɪʃ/", "v. 出版；发表；公布", "verb", 2),
    ("purchase", "/ˈpɜːrtʃəs/", "v. 购买；采购；获得", "verb", 2),
    ("pursue", "/pərˈsuː/", "v. 追求；追赶；从事", "verb", 2),
    ("qualify", "/ˈkwɑːlɪfaɪ/", "v. 使合格；取得资格；限定", "verb", 3),
    ("quit", "/kwɪt/", "v. 放弃；退出；辞职", "verb", 2),
    ("react", "/riˈækt/", "v. 反应；回应；起反应", "verb", 2),
    ("rebel", "/rɪˈbel/", "v. 反抗；造反；叛逆", "verb", 3),
    ("recall", "/rɪˈkɔːl/", "v. 回忆；召回；撤销", "verb", 2),
    ("reckon", "/ˈrekən/", "v. 认为；估计；计算", "verb", 3),
    ("recommend", "/ˌrekəˈmend/", "v. 推荐；建议；劝告", "verb", 2),
    ("recover", "/rɪˈkʌvər/", "v. 恢复；康复；找回", "verb", 2),
    ("reduce", "/rɪˈduːs/", "v. 减少；降低；缩减", "verb", 2),
    ("refer", "/rɪˈfɜːr/", "v. 提到；参考；涉及", "verb", 2),
    ("reflect", "/rɪˈflekt/", "v. 反映；反射；思考", "verb", 2),
    ("refuse", "/rɪˈfjuːz/", "v. 拒绝；回绝；不肯", "verb", 1),
    ("regulate", "/ˈreɡjuleɪt/", "v. 调节；管理；控制", "verb", 3),
    ("reinforce", "/ˌriːɪnˈfɔːrs/", "v. 加强；加固；增援", "verb", 3),
    ("reject", "/rɪˈdʒekt/", "v. 拒绝；排斥；驳回", "verb", 2),
    ("release", "/rɪˈliːs/", "v. 释放；发布；发行", "verb", 2),
    ("relieve", "/rɪˈliːv/", "v. 缓解；减轻；解除", "verb", 2),
    ("rely", "/rɪˈlaɪ/", "v. 依赖；依靠；信赖", "verb", 2),
    ("remark", "/rɪˈmɑːrk/", "v. 评论；注意到；说起", "verb", 3),
    ("remedy", "/ˈremədi/", "v. 补救；纠正；治疗", "verb", 3),
    ("render", "/ˈrendər/", "v. 使成为；提供；给予", "verb", 3),
    ("replace", "/rɪˈpleɪs/", "v. 取代；替换；放回", "verb", 2),
    ("represent", "/ˌreprɪˈzent/", "v. 代表；表示；描绘", "verb", 2),
    ("reproduce", "/ˌriːprəˈduːs/", "v. 复制；繁殖；再现", "verb", 3),
    ("request", "/rɪˈkwest/", "v. 请求；要求；恳请", "verb", 2),
    ("require", "/rɪˈkwaɪər/", "v. 需要；要求；命令", "verb", 2),
    ("resemble", "/rɪˈzembl/", "v. 像；类似；相似", "verb", 3),
    ("reserve", "/rɪˈzɜːrv/", "v. 保留；预订；储备", "verb", 2),
    ("resign", "/rɪˈzaɪn/", "v. 辞职；放弃；屈从", "verb", 3),
    ("resist", "/rɪˈzɪst/", "v. 抵抗；抵制；忍耐", "verb", 2),
    ("resolve", "/rɪˈzɑːlv/", "v. 解决；决心；分解", "verb", 2),
    ("resort", "/rɪˈzɔːrt/", "v. 诉诸；求助；常去", "verb", 3),
    ("respond", "/rɪˈspɑːnd/", "v. 回答；回应；做出反应", "verb", 2),
    ("restore", "/rɪˈstɔːr/", "v. 恢复；修复；归还", "verb", 3),
    ("restrain", "/rɪˈstreɪn/", "v. 抑制；约束；阻止", "verb", 3),
    ("restrict", "/rɪˈstrɪkt/", "v. 限制；约束；限定", "verb", 3),
    ("resume", "/rɪˈzuːm/", "v. 恢复；重新开始；继续", "verb", 3),
    ("retain", "/rɪˈteɪn/", "v. 保留；保持；记住", "verb", 3),
    ("retire", "/rɪˈtaɪər/", "v. 退休；退役；退隐", "verb", 2),
    ("reveal", "/rɪˈviːl/", "v. 揭示；透露；显示", "verb", 2),
    ("revolutionize", "/ˌrevəˈluːʃənaɪz/", "v. 彻底改变；引发革命", "verb", 4),
    ("reward", "/rɪˈwɔːrd/", "v. 奖励；奖赏；回报", "verb", 2),
    ("rid", "/rɪd/", "v. 摆脱；除去；清除", "verb", 2),
    ("ruin", "/ˈruːɪn/", "v. 毁坏；破坏；使破产", "verb", 2),
    ("sacrifice", "/ˈsækrɪfaɪs/", "v. 牺牲；献出；献祭", "verb", 3),
    ("satisfy", "/ˈsætɪsfaɪ/", "v. 满足；使满意；符合", "verb", 2),
    ("scan", "/skæn/", "v. 扫描；浏览；细看", "verb", 2),
    ("secure", "/sɪˈkjʊr/", "v. 获得；使安全；固定", "verb", 2),
    ("seek", "/siːk/", "v. 寻找；寻求；试图", "verb", 2),
    ("seize", "/siːz/", "v. 抓住；夺取；把握", "verb", 2),
    ("shelter", "/ˈʃeltər/", "v. 庇护；躲避；保护", "verb", 2),
    ("shrink", "/ʃrɪŋk/", "v. 收缩；缩小；退缩", "verb", 3),
    ("simplify", "/ˈsɪmplɪfaɪ/", "v. 简化；精简；使简易", "verb", 2),
    ("sow", "/soʊ/", "v. 播种；散布；激起", "verb", 3),
    ("specify", "/ˈspesɪfaɪ/", "v. 明确说明；指定；详述", "verb", 3),
    ("squeeze", "/skwiːz/", "v. 挤压；压榨；挤入", "verb", 2),
    ("stain", "/steɪn/", "v. 染色；玷污；弄脏", "verb", 3),
    ("starve", "/stɑːrv/", "v. 挨饿；饿死；渴望", "verb", 2),
    ("stimulate", "/ˈstɪmjuleɪt/", "v. 刺激；激励；促进", "verb", 3),
    ("strengthen", "/ˈstreŋθən/", "v. 加强；增强；巩固", "verb", 2),
    ("strive", "/straɪv/", "v. 努力；奋斗；力争", "verb", 3),
    ("submit", "/səbˈmɪt/", "v. 提交；呈递；服从", "verb", 2),
    ("substitute", "/ˈsʌbstɪtuːt/", "v. 替代；替换；代替", "verb", 2),
    ("suffer", "/ˈsʌfər/", "v. 遭受；忍受；受苦", "verb", 2),
    ("suggest", "/səˈdʒest/", "v. 建议；暗示；表明", "verb", 1),
    ("supplement", "/ˈsʌplɪment/", "v. 补充；增补；添加", "verb", 3),
    ("surrender", "/səˈrendər/", "v. 投降；屈服；放弃", "verb", 3),
    ("surround", "/səˈraʊnd/", "v. 包围；环绕；围绕", "verb", 2),
    ("survive", "/sərˈvaɪv/", "v. 生存；幸存；比…活得长", "verb", 2),
    ("suspect", "/səˈspekt/", "v. 怀疑；猜想；觉得", "verb", 2),
    ("suspend", "/səˈspend/", "v. 暂停；悬挂；使停职", "verb", 3),
    ("sustain", "/səˈsteɪn/", "v. 维持；支撑；遭受", "verb", 3),
    ("swallow", "/ˈswɑːloʊ/", "v. 吞下；咽下；忍受", "verb", 2),
    ("symbolize", "/ˈsɪmbəlaɪz/", "v. 象征；代表；标志", "verb", 3),
    ("tackle", "/ˈtækl/", "v. 处理；解决；对付", "verb", 2),
    ("tempt", "/tempt/", "v. 诱惑；引诱；吸引", "verb", 3),
    ("tend", "/tend/", "v. 倾向；趋向；照顾", "verb", 2),
    ("threaten", "/ˈθretn/", "v. 威胁；恐吓；预示", "verb", 2),
    ("tolerate", "/ˈtɑːləreɪt/", "v. 容忍；忍受；宽容", "verb", 3),
    ("transform", "/trænsˈfɔːrm/", "v. 改变；转变；改造", "verb", 2),
    ("tremble", "/ˈtrembl/", "v. 颤抖；发抖；焦虑", "verb", 2),
    ("undergo", "/ˌʌndərˈɡoʊ/", "v. 经历；遭受；接受", "verb", 3),
    ("undermine", "/ˌʌndərˈmaɪn/", "v. 削弱；破坏；暗中损害", "verb", 4),
    ("undertake", "/ˌʌndərˈteɪk/", "v. 从事；承担；承诺", "verb", 3),
    ("unite", "/juˈnaɪt/", "v. 团结；联合；统一", "verb", 2),
    ("urge", "/ɜːrdʒ/", "v. 催促；力劝；强烈要求", "verb", 3),
    ("utilize", "/ˈjuːtɪlaɪz/", "v. 利用；使用；应用", "verb", 3),
    ("vanish", "/ˈvænɪʃ/", "v. 消失；消散；绝迹", "verb", 3),
    ("vary", "/ˈveri/", "v. 变化；不同；改变", "verb", 2),
    ("violate", "/ˈvaɪəleɪt/", "v. 违反；侵犯；亵渎", "verb", 3),
    ("wander", "/ˈwɑːndər/", "v. 漫步；闲逛；走神", "verb", 2),
    ("weaken", "/ˈwiːkən/", "v. 削弱；减弱；变弱", "verb", 2),
    ("withdraw", "/wɪðˈdrɔː/", "v. 撤回；退出；取款", "verb", 3),
    ("witness", "/ˈwɪtnəs/", "v. 目睹；见证；作证", "verb", 2),
    ("worship", "/ˈwɜːrʃɪp/", "v. 崇拜；敬奉；爱慕", "verb", 3),
    ("yield", "/jiːld/", "v. 产出；屈服；让出", "verb", 3),

    # ── Nouns (名词) ─────────────────────────────────
    ("abundance", "/əˈbʌndəns/", "n. 丰富；充裕；大量", "noun", 3),
    ("access", "/ˈækses/", "n. 通道；进入；使用权", "noun", 2),
    ("accommodation", "/əˌkɑːməˈdeɪʃn/", "n. 住宿；适应；调解", "noun", 3),
    ("achievement", "/əˈtʃiːvmənt/", "n. 成就；成绩；达到", "noun", 2),
    ("adversity", "/ədˈvɜːrsəti/", "n. 逆境；不幸；灾难", "noun", 4),
    ("agenda", "/əˈdʒendə/", "n. 议程；日程；议事单", "noun", 3),
    ("ambition", "/æmˈbɪʃn/", "n. 雄心；野心；抱负", "noun", 2),
    ("ancestor", "/ˈænsestər/", "n. 祖先；祖宗；原型", "noun", 2),
    ("angle", "/ˈæŋɡl/", "n. 角度；角；观点", "noun", 2),
    ("appetite", "/ˈæpɪtaɪt/", "n. 食欲；胃口；欲望", "noun", 2),
    ("appliance", "/əˈplaɪəns/", "n. 电器；器具；设备", "noun", 3),
    ("approach", "/əˈproʊtʃ/", "n. 方法；途径；接近", "noun", 2),
    ("architecture", "/ˈɑːrkɪtektʃər/", "n. 建筑；建筑学；结构", "noun", 3),
    ("aspect", "/ˈæspekt/", "n. 方面；层面；外观", "noun", 2),
    ("assembly", "/əˈsembli/", "n. 集会；装配；议会", "noun", 3),
    ("atmosphere", "/ˈætməsfɪr/", "n. 大气；气氛；环境", "noun", 2),
    ("authority", "/əˈθɔːrəti/", "n. 权威；当局；权力", "noun", 2),
    ("bacteria", "/bækˈtɪriə/", "n. 细菌（复数）", "noun", 3),
    ("barrier", "/ˈbæriər/", "n. 障碍；屏障；栅栏", "noun", 2),
    ("benefit", "/ˈbenɪfɪt/", "n. 利益；好处；福利", "noun", 2),
    ("beverage", "/ˈbevərɪdʒ/", "n. 饮料；饮品", "noun", 3),
    ("boundary", "/ˈbaʊndri/", "n. 边界；界限；分界线", "noun", 3),
    ("brand", "/brænd/", "n. 品牌；商标；类型", "noun", 2),
    ("budget", "/ˈbʌdʒɪt/", "n. 预算；经费", "noun", 2),
    ("burden", "/ˈbɜːrdn/", "n. 负担；重担；责任", "noun", 2),
    ("campaign", "/kæmˈpeɪn/", "n. 运动；战役；活动", "noun", 2),
    ("capability", "/ˌkeɪpəˈbɪləti/", "n. 能力；才能；容量", "noun", 3),
    ("capacity", "/kəˈpæsəti/", "n. 容量；能力；职位", "noun", 2),
    ("circumstance", "/ˈsɜːrkəmstæns/", "n. 环境；情况；境遇", "noun", 3),
    ("civilization", "/ˌsɪvələˈzeɪʃn/", "n. 文明；文化；开化", "noun", 3),
    ("climate", "/ˈklaɪmət/", "n. 气候；风气；氛围", "noun", 2),
    ("commodity", "/kəˈmɑːdəti/", "n. 商品；货物；日用品", "noun", 3),
    ("community", "/kəˈmjuːnəti/", "n. 社区；社会；团体", "noun", 2),
    ("competence", "/ˈkɑːmpɪtəns/", "n. 能力；胜任；技能", "noun", 3),
    ("component", "/kəmˈpoʊnənt/", "n. 组成部分；部件；成分", "noun", 3),
    ("concept", "/ˈkɑːnsept/", "n. 概念；观念；想法", "noun", 2),
    ("conference", "/ˈkɑːnfərəns/", "n. 会议；讨论会；协商会", "noun", 2),
    ("confidence", "/ˈkɑːnfɪdəns/", "n. 信心；信任；自信", "noun", 2),
    ("conflict", "/ˈkɑːnflɪkt/", "n. 冲突；矛盾；斗争", "noun", 2),
    ("consequence", "/ˈkɑːnsɪkwens/", "n. 结果；后果；重要性", "noun", 3),
    ("conservation", "/ˌkɑːnsərˈveɪʃn/", "n. 保护；保存；节约", "noun", 3),
    ("constitution", "/ˌkɑːnstɪˈtuːʃn/", "n. 宪法；章程；构成", "noun", 4),
    ("consumption", "/kənˈsʌmpʃn/", "n. 消费；消耗；消耗量", "noun", 3),
    ("context", "/ˈkɑːntekst/", "n. 上下文；背景；语境", "noun", 2),
    ("controversy", "/ˈkɑːntrəvɜːrsi/", "n. 争议；争论；辩论", "noun", 3),
    ("convenience", "/kənˈviːniəns/", "n. 方便；便利；便利设施", "noun", 2),
    ("corporation", "/ˌkɔːrpəˈreɪʃn/", "n. 公司；企业；法人", "noun", 2),
    ("craft", "/kræft/", "n. 工艺；手艺；技能", "noun", 3),
    ("crisis", "/ˈkraɪsɪs/", "n. 危机；紧要关头；转折点", "noun", 2),
    ("criterion", "/kraɪˈtɪriən/", "n. 标准；准则；尺度", "noun", 4),
    ("currency", "/ˈkɜːrənsi/", "n. 货币；通货；流通", "noun", 3),
    ("debate", "/dɪˈbeɪt/", "n. 辩论；争论；讨论", "noun", 2),
    ("decline", "/dɪˈklaɪn/", "n. 下降；衰退；减少", "noun", 3),
    ("democracy", "/dɪˈmɑːkrəsi/", "n. 民主；民主制度；民主国家", "noun", 3),
    ("depression", "/dɪˈpreʃn/", "n. 沮丧；萧条；洼地", "noun", 3),
    ("destination", "/ˌdestɪˈneɪʃn/", "n. 目的地；终点；目标", "noun", 2),
    ("dilemma", "/dɪˈlemə/", "n. 困境；两难境地", "noun", 4),
    ("diploma", "/dɪˈploʊmə/", "n. 文凭；毕业证书；奖状", "noun", 3),
    ("disaster", "/dɪˈzæstər/", "n. 灾难；灾祸；不幸", "noun", 2),
    ("discipline", "/ˈdɪsəplɪn/", "n. 纪律；学科；训练", "noun", 3),
    ("discount", "/ˈdɪskaʊnt/", "n. 折扣；贴现", "noun", 2),
    ("diversity", "/daɪˈvɜːrsəti/", "n. 多样性；差异；多元化", "noun", 3),
    ("economy", "/ɪˈkɑːnəmi/", "n. 经济；节约；理财", "noun", 2),
    ("efficiency", "/ɪˈfɪʃnsi/", "n. 效率；效能；功效", "noun", 3),
    ("enterprise", "/ˈentərpraɪz/", "n. 企业；事业；进取心", "noun", 3),
    ("enthusiasm", "/ɪnˈθuːziæzəm/", "n. 热情；热忱；热衷", "noun", 2),
    ("environment", "/ɪnˈvaɪrənmənt/", "n. 环境；周围；自然", "noun", 2),
    ("equipment", "/ɪˈkwɪpmənt/", "n. 设备；装备；器材", "noun", 2),
    ("evidence", "/ˈevɪdəns/", "n. 证据；迹象；明显", "noun", 2),
    ("exception", "/ɪkˈsepʃn/", "n. 例外；除外；异议", "noun", 2),
    ("existence", "/ɪɡˈzɪstəns/", "n. 存在；生存；生活", "noun", 2),
    ("expectation", "/ˌekspekˈteɪʃn/", "n. 期望；预期；期待", "noun", 2),
    ("expense", "/ɪkˈspens/", "n. 费用；花费；代价", "noun", 2),
    ("expertise", "/ˌekspɜːrˈtiːz/", "n. 专门知识；专长；技能", "noun", 4),
    ("explosion", "/ɪkˈsploʊʒn/", "n. 爆炸；激增；爆发", "noun", 2),
    ("facility", "/fəˈsɪləti/", "n. 设施；设备；能力", "noun", 2),
    ("famine", "/ˈfæmɪn/", "n. 饥荒；饥饿；严重缺乏", "noun", 3),
    ("fashion", "/ˈfæʃn/", "n. 时尚；时装；方式", "noun", 2),
    ("feature", "/ˈfiːtʃər/", "n. 特征；特色；面貌", "noun", 2),
    ("feedback", "/ˈfiːdbæk/", "n. 反馈；回馈；反应", "noun", 2),
    ("fortune", "/ˈfɔːrtʃən/", "n. 财富；运气；命运", "noun", 2),
    ("foundation", "/faʊnˈdeɪʃn/", "n. 基础；基金会；建立", "noun", 2),
    ("framework", "/ˈfreɪmwɜːrk/", "n. 框架；结构；体系", "noun", 3),
    ("freedom", "/ˈfriːdəm/", "n. 自由；自主；免除", "noun", 1),
    ("frontier", "/frʌnˈtɪr/", "n. 边境；前沿；边疆", "noun", 3),
    ("fuel", "/ˈfjuːəl/", "n. 燃料；动力；刺激物", "noun", 2),
    ("gender", "/ˈdʒendər/", "n. 性别；性", "noun", 2),
    ("genius", "/ˈdʒiːniəs/", "n. 天才；天赋；才智", "noun", 2),
    ("gesture", "/ˈdʒestʃər/", "n. 手势；姿态；表示", "noun", 2),
    ("gratitude", "/ˈɡrætɪtuːd/", "n. 感激；感谢；感恩", "noun", 2),
    ("guarantee", "/ˌɡærənˈtiː/", "n. 保证；担保；保证书", "noun", 2),
    ("habitat", "/ˈhæbɪtæt/", "n. 栖息地；产地；居住地", "noun", 3),
    ("heritage", "/ˈherɪtɪdʒ/", "n. 遗产；传统；继承物", "noun", 3),
    ("horizon", "/həˈraɪzn/", "n. 地平线；眼界；范围", "noun", 3),
    ("hospitality", "/ˌhɑːspɪˈtæləti/", "n. 好客；殷勤；款待", "noun", 3),
    ("household", "/ˈhaʊshoʊld/", "n. 家庭；户；一家人", "noun", 2),
    ("identity", "/aɪˈdentəti/", "n. 身份；认同；特性", "noun", 2),
    ("impact", "/ˈɪmpækt/", "n. 影响；冲击；撞击", "noun", 2),
    ("incident", "/ˈɪnsɪdənt/", "n. 事件；事变；插曲", "noun", 2),
    ("individual", "/ˌɪndɪˈvɪdʒuəl/", "n. 个人；个体", "noun", 2),
    ("infection", "/ɪnˈfekʃn/", "n. 感染；传染；传染病", "noun", 3),
    ("infrastructure", "/ˈɪnfrəstrʌktʃər/", "n. 基础设施；基础建设", "noun", 4),
    ("innovation", "/ˌɪnəˈveɪʃn/", "n. 创新；革新；新事物", "noun", 3),
    ("instinct", "/ˈɪnstɪŋkt/", "n. 本能；直觉；天性", "noun", 3),
    ("institution", "/ˌɪnstɪˈtuːʃn/", "n. 机构；制度；建立", "noun", 3),
    ("intelligence", "/ɪnˈtelɪdʒəns/", "n. 智力；情报；智能", "noun", 2),
    ("interaction", "/ˌɪntərˈækʃn/", "n. 互动；相互作用；交流", "noun", 3),
    ("investment", "/ɪnˈvestmənt/", "n. 投资；投入；投资额", "noun", 3),
    ("isolation", "/ˌaɪsəˈleɪʃn/", "n. 隔离；孤立；孤独", "noun", 3),
    ("justice", "/ˈdʒʌstɪs/", "n. 正义；公正；司法", "noun", 2),
    ("knowledge", "/ˈnɑːlɪdʒ/", "n. 知识；学识；了解", "noun", 1),
    ("landscape", "/ˈlændskeɪp/", "n. 风景；景观；地貌", "noun", 2),
    ("liberty", "/ˈlɪbərti/", "n. 自由；自由权；许可", "noun", 3),
    ("likelihood", "/ˈlaɪklihʊd/", "n. 可能性；概率", "noun", 3),
    ("limitation", "/ˌlɪmɪˈteɪʃn/", "n. 限制；局限；限度", "noun", 3),
    ("literature", "/ˈlɪtərətʃər/", "n. 文学；文献；著作", "noun", 2),
    ("maintenance", "/ˈmeɪntənəns/", "n. 维护；保养；维持", "noun", 3),
    ("mechanism", "/ˈmekənɪzəm/", "n. 机制；机械；办法", "noun", 3),
    ("merchant", "/ˈmɜːrtʃənt/", "n. 商人；店主；批发商", "noun", 2),
    ("mercy", "/ˈmɜːrsi/", "n. 仁慈；怜悯；宽恕", "noun", 3),
    ("mission", "/ˈmɪʃn/", "n. 使命；任务；代表团", "noun", 2),
    ("motive", "/ˈmoʊtɪv/", "n. 动机；目的；原因", "noun", 3),
    ("negotiation", "/nɪˌɡoʊʃiˈeɪʃn/", "n. 谈判；协商；交涉", "noun", 3),
    ("network", "/ˈnetwɜːrk/", "n. 网络；关系网；广播网", "noun", 2),
    ("notion", "/ˈnoʊʃn/", "n. 概念；观念；想法", "noun", 3),
    ("nucleus", "/ˈnuːkliəs/", "n. 核心；核；原子核", "noun", 3),
    ("obligation", "/ˌɑːblɪˈɡeɪʃn/", "n. 义务；责任；债务", "noun", 3),
    ("occupation", "/ˌɑːkjuˈpeɪʃn/", "n. 职业；占领；占据", "noun", 3),
    ("offspring", "/ˈɔːfsprɪŋ/", "n. 后代；子女；产物", "noun", 3),
    ("opportunity", "/ˌɑːpərˈtuːnəti/", "n. 机会；时机；良机", "noun", 2),
    ("outcome", "/ˈaʊtkʌm/", "n. 结果；结局；后果", "noun", 2),
    ("parliament", "/ˈpɑːrləmənt/", "n. 议会；国会；议院", "noun", 3),
    ("passion", "/ˈpæʃn/", "n. 激情；热情；热爱", "noun", 2),
    ("patience", "/ˈpeɪʃns/", "n. 耐心；忍耐；耐力", "noun", 2),
    ("penalty", "/ˈpenəlti/", "n. 惩罚；处罚；罚金", "noun", 3),
    ("perception", "/pərˈsepʃn/", "n. 感知；看法；洞察力", "noun", 3),
    ("personality", "/ˌpɜːrsəˈnæləti/", "n. 个性；人格；性格", "noun", 2),
    ("perspective", "/pərˈspektɪv/", "n. 视角；观点；远景", "noun", 3),
    ("phenomenon", "/fɪˈnɑːmɪnən/", "n. 现象；奇迹；非凡的人", "noun", 3),
    ("philosophy", "/fɪˈlɑːsəfi/", "n. 哲学；人生观；哲理", "noun", 3),
    ("pledge", "/pledʒ/", "n. 誓言；保证；抵押", "noun", 3),
    ("policy", "/ˈpɑːləsi/", "n. 政策；方针；保险单", "noun", 2),
    ("pollution", "/pəˈluːʃn/", "n. 污染；玷污；污染物", "noun", 2),
    ("potential", "/pəˈtenʃl/", "n. 潜力；潜能；可能性", "noun", 2),
    ("poverty", "/ˈpɑːvərti/", "n. 贫穷；贫困；缺乏", "noun", 2),
    ("precaution", "/prɪˈkɔːʃn/", "n. 预防；警惕；防范", "noun", 3),
    ("prejudice", "/ˈpredʒudɪs/", "n. 偏见；歧视；成见", "noun", 3),
    ("presence", "/ˈprezns/", "n. 存在；出席；在场", "noun", 2),
    ("principle", "/ˈprɪnsəpl/", "n. 原则；原理；准则", "noun", 2),
    ("priority", "/praɪˈɔːrəti/", "n. 优先；优先权；重点", "noun", 3),
    ("privilege", "/ˈprɪvəlɪdʒ/", "n. 特权；优惠；荣幸", "noun", 3),
    ("procedure", "/prəˈsiːdʒər/", "n. 程序；步骤；手续", "noun", 3),
    ("profession", "/prəˈfeʃn/", "n. 职业；行业；专业", "noun", 2),
    ("prosperity", "/prɑːˈsperəti/", "n. 繁荣；兴旺；成功", "noun", 3),
    ("provision", "/prəˈvɪʒn/", "n. 规定；供应；条款", "noun", 3),
    ("psychology", "/saɪˈkɑːlədʒi/", "n. 心理学；心理；心理状态", "noun", 3),
    ("qualification", "/ˌkwɑːlɪfɪˈkeɪʃn/", "n. 资格；条件；限制", "noun", 3),
    ("quantity", "/ˈkwɑːntəti/", "n. 数量；量；大量", "noun", 2),
    ("recession", "/rɪˈseʃn/", "n. 衰退；不景气；后退", "noun", 3),
    ("recognition", "/ˌrekəɡˈnɪʃn/", "n. 识别；认可；承认", "noun", 3),
    ("reputation", "/ˌrepjuˈteɪʃn/", "n. 名声；声誉；名誉", "noun", 2),
    ("resource", "/ˈriːsɔːrs/", "n. 资源；财力；智谋", "noun", 2),
    ("responsibility", "/rɪˌspɑːnsəˈbɪləti/", "n. 责任；职责；义务", "noun", 2),
    ("restriction", "/rɪˈstrɪkʃn/", "n. 限制；约束；规定", "noun", 3),
    ("revenue", "/ˈrevənuː/", "n. 收入；税收；收益", "noun", 3),
    ("revolution", "/ˌrevəˈluːʃn/", "n. 革命；变革；旋转", "noun", 2),
    ("routine", "/ruːˈtiːn/", "n. 常规；例行公事；惯例", "noun", 2),
    ("sacrifice", "/ˈsækrɪfaɪs/", "n. 牺牲；献祭；牺牲品", "noun", 3),
    ("scholarship", "/ˈskɑːlərʃɪp/", "n. 奖学金；学问；学识", "noun", 2),
    ("sensation", "/senˈseɪʃn/", "n. 感觉；轰动；知觉", "noun", 3),
    ("shelter", "/ˈʃeltər/", "n. 庇护所；避难所；遮盖", "noun", 2),
    ("shortage", "/ˈʃɔːrtɪdʒ/", "n. 缺乏；不足；短缺", "noun", 2),
    ("significance", "/sɪɡˈnɪfɪkəns/", "n. 重要性；意义；显著性", "noun", 3),
    ("species", "/ˈspiːʃiːz/", "n. 物种；种类；类型", "noun", 2),
    ("stereotype", "/ˈsteriətaɪp/", "n. 刻板印象；成见；陈规", "noun", 4),
    ("strategy", "/ˈstrætədʒi/", "n. 策略；战略；规划", "noun", 2),
    ("substance", "/ˈsʌbstəns/", "n. 物质；实质；内容", "noun", 3),
    ("surgery", "/ˈsɜːrdʒəri/", "n. 外科手术；手术室", "noun", 3),
    ("symptom", "/ˈsɪmptəm/", "n. 症状；征兆；迹象", "noun", 3),
    ("talent", "/ˈtælənt/", "n. 才能；天赋；人才", "noun", 2),
    ("tendency", "/ˈtendənsi/", "n. 趋势；倾向；癖好", "noun", 2),
    ("tolerance", "/ˈtɑːlərəns/", "n. 宽容；忍耐；公差", "noun", 3),
    ("tradition", "/trəˈdɪʃn/", "n. 传统；惯例；传说", "noun", 2),
    ("tragedy", "/ˈtrædʒədi/", "n. 悲剧；灾难；不幸", "noun", 3),
    ("trend", "/trend/", "n. 趋势；潮流；走向", "noun", 2),
    ("ultimate", "/ˈʌltɪmət/", "n. 终极；极限；顶点", "noun", 3),
    ("universe", "/ˈjuːnɪvɜːrs/", "n. 宇宙；世界；领域", "noun", 2),
    ("validity", "/vəˈlɪdəti/", "n. 有效性；合法性；正确性", "noun", 4),
    ("venture", "/ˈventʃər/", "n. 冒险；风险项目；企业", "noun", 3),
    ("victim", "/ˈvɪktɪm/", "n. 受害者；牺牲品；受骗者", "noun", 2),
    ("virtue", "/ˈvɜːrtʃuː/", "n. 美德；优点；德行", "noun", 3),
    ("vision", "/ˈvɪʒn/", "n. 视力；愿景；远见", "noun", 2),
    ("volume", "/ˈvɑːljuːm/", "n. 体积；音量；卷；册", "noun", 2),
    ("welfare", "/ˈwelfer/", "n. 福利；幸福；安康", "noun", 2),
    ("wisdom", "/ˈwɪzdəm/", "n. 智慧；明智；知识", "noun", 2),
    ("witness", "/ˈwɪtnəs/", "n. 目击者；证人；证据", "noun", 2),

    # ── Adjectives (形容词) ──────────────────────────
    ("absolute", "/ˈæbsəluːt/", "adj. 绝对的；完全的；毋庸置疑的", "adjective", 3),
    ("abstract", "/ˈæbstrækt/", "adj. 抽象的；理论的；深奥的", "adjective", 3),
    ("abundant", "/əˈbʌndənt/", "adj. 丰富的；充足的；大量的", "adjective", 3),
    ("accurate", "/ˈækjərət/", "adj. 准确的；精确的；正确的", "adjective", 2),
    ("adequate", "/ˈædɪkwət/", "adj. 足够的；适当的；胜任的", "adjective", 3),
    ("aggressive", "/əˈɡresɪv/", "adj. 侵略的；好斗的；进取的", "adjective", 2),
    ("alert", "/əˈlɜːrt/", "adj. 警觉的；警惕的；机敏的", "adjective", 2),
    ("alternative", "/ɔːlˈtɜːrnətɪv/", "adj. 替代的；另类的；其他的", "adjective", 2),
    ("ambiguous", "/æmˈbɪɡjuəs/", "adj. 模糊的；含糊的；不明确的", "adjective", 4),
    ("ambitious", "/æmˈbɪʃəs/", "adj. 有雄心的；野心勃勃的", "adjective", 2),
    ("anxious", "/ˈæŋkʃəs/", "adj. 焦虑的；担忧的；渴望的", "adjective", 2),
    ("apparent", "/əˈpærənt/", "adj. 明显的；表面上的；显然的", "adjective", 3),
    ("appropriate", "/əˈproʊpriət/", "adj. 适当的；合适的；恰当的", "adjective", 2),
    ("artificial", "/ˌɑːrtɪˈfɪʃl/", "adj. 人工的；人造的；虚假的", "adjective", 2),
    ("autonomous", "/ɔːˈtɑːnəməs/", "adj. 自治的；自主的；独立的", "adjective", 4),
    ("available", "/əˈveɪləbl/", "adj. 可用的；可获得的；有效的", "adjective", 2),
    ("aware", "/əˈwer/", "adj. 意识到的；知道的；察觉的", "adjective", 2),
    ("bare", "/ber/", "adj. 裸露的；光秃的；空的", "adjective", 2),
    ("beneficial", "/ˌbenɪˈfɪʃl/", "adj. 有益的；有利的；有帮助的", "adjective", 2),
    ("bold", "/boʊld/", "adj. 大胆的；勇敢的；醒目的", "adjective", 2),
    ("brief", "/briːf/", "adj. 简短的；简洁的；短暂的", "adjective", 2),
    ("capable", "/ˈkeɪpəbl/", "adj. 有能力的；能胜任的", "adjective", 2),
    ("casual", "/ˈkæʒuəl/", "adj. 随意的；偶然的；非正式的", "adjective", 2),
    ("chronic", "/ˈkrɑːnɪk/", "adj. 慢性的；长期的；习惯性的", "adjective", 4),
    ("cognitive", "/ˈkɑːɡnətɪv/", "adj. 认知的；认识的；感知的", "adjective", 4),
    ("commercial", "/kəˈmɜːrʃl/", "adj. 商业的；贸易的；营利的", "adjective", 2),
    ("compatible", "/kəmˈpætəbl/", "adj. 兼容的；相容的；合得来的", "adjective", 3),
    ("competent", "/ˈkɑːmpɪtənt/", "adj. 有能力的；胜任的；称职的", "adjective", 3),
    ("complex", "/kəmˈpleks/", "adj. 复杂的；复合的；难懂的", "adjective", 2),
    ("comprehensive", "/ˌkɑːmprɪˈhensɪv/", "adj. 全面的；综合的；广泛的", "adjective", 3),
    ("conscious", "/ˈkɑːnʃəs/", "adj. 有意识的；清醒的；自觉的", "adjective", 2),
    ("conservative", "/kənˈsɜːrvətɪv/", "adj. 保守的；守旧的；谨慎的", "adjective", 3),
    ("considerate", "/kənˈsɪdərət/", "adj. 体贴的；考虑周到的；体谅的", "adjective", 3),
    ("consistent", "/kənˈsɪstənt/", "adj. 一致的；始终如一的；连贯的", "adjective", 3),
    ("contemporary", "/kənˈtempəreri/", "adj. 当代的；同时代的；现代的", "adjective", 3),
    ("controversial", "/ˌkɑːntrəˈvɜːrʃl/", "adj. 有争议的；引起争论的", "adjective", 3),
    ("conventional", "/kənˈvenʃənl/", "adj. 传统的；常规的；惯例的", "adjective", 3),
    ("crucial", "/ˈkruːʃl/", "adj. 关键的；至关重要的；决定性的", "adjective", 3),
    ("curious", "/ˈkjʊriəs/", "adj. 好奇的；求知欲强的；奇特的", "adjective", 2),
    ("decent", "/ˈdiːsnt/", "adj. 体面的；正派的；相当好的", "adjective", 2),
    ("delicate", "/ˈdelɪkət/", "adj. 精致的；脆弱的；微妙的", "adjective", 3),
    ("dense", "/dens/", "adj. 密集的；稠密的；浓的", "adjective", 2),
    ("depressed", "/dɪˈprest/", "adj. 沮丧的；萧条的；压抑的", "adjective", 2),
    ("desperate", "/ˈdespərət/", "adj. 绝望的；不顾一切的；极度的", "adjective", 3),
    ("diverse", "/daɪˈvɜːrs/", "adj. 多样的；不同的；多元的", "adjective", 2),
    ("dominant", "/ˈdɑːmɪnənt/", "adj. 主导的；支配的；占优势的", "adjective", 3),
    ("dramatic", "/drəˈmætɪk/", "adj. 戏剧性的；巨大的；引人注目的", "adjective", 2),
    ("durable", "/ˈdʊrəbl/", "adj. 耐用的；持久的；经久的", "adjective", 2),
    ("dynamic", "/daɪˈnæmɪk/", "adj. 动态的；充满活力的；不断变化的", "adjective", 3),
    ("efficient", "/ɪˈfɪʃnt/", "adj. 高效的；有效率的；能干的", "adjective", 2),
    ("elaborate", "/ɪˈlæbərət/", "adj. 精心制作的；详尽的；复杂的", "adjective", 3),
    ("elegant", "/ˈelɪɡənt/", "adj. 优雅的；精美的；简洁的", "adjective", 2),
    ("enormous", "/ɪˈnɔːrməs/", "adj. 巨大的；庞大的；极大的", "adjective", 2),
    ("essential", "/ɪˈsenʃl/", "adj. 必要的；本质的；基本的", "adjective", 2),
    ("eternal", "/ɪˈtɜːrnl/", "adj. 永恒的；永久的；无休止的", "adjective", 3),
    ("eventual", "/ɪˈventʃuəl/", "adj. 最终的；最后的；结果的", "adjective", 3),
    ("excessive", "/ɪkˈsesɪv/", "adj. 过度的；过多的；极度的", "adjective", 3),
    ("explicit", "/ɪkˈsplɪsɪt/", "adj. 明确的；清楚的；直言的", "adjective", 3),
    ("extensive", "/ɪkˈstensɪv/", "adj. 广泛的；大量的；广阔的", "adjective", 2),
    ("external", "/ɪkˈstɜːrnl/", "adj. 外部的；外面的；外来的", "adjective", 2),
    ("extraordinary", "/ɪkˈstrɔːrdəneri/", "adj. 非凡的；特别的；卓越的", "adjective", 3),
    ("fatal", "/ˈfeɪtl/", "adj. 致命的；毁灭性的；重大的", "adjective", 3),
    ("feasible", "/ˈfiːzəbl/", "adj. 可行的；可能的；合理的", "adjective", 3),
    ("fertile", "/ˈfɜːrtl/", "adj. 肥沃的；富饶的；多产的", "adjective", 3),
    ("flexible", "/ˈfleksəbl/", "adj. 灵活的；柔韧的；可变通的", "adjective", 2),
    ("fragile", "/ˈfrædʒl/", "adj. 脆弱的；易碎的；纤弱的", "adjective", 3),
    ("frequent", "/ˈfriːkwənt/", "adj. 频繁的；经常的；常见的", "adjective", 2),
    ("fundamental", "/ˌfʌndəˈmentl/", "adj. 基本的；根本的；基础的", "adjective", 3),
    ("generous", "/ˈdʒenərəs/", "adj. 慷慨的；大方的；宽宏大量的", "adjective", 2),
    ("genuine", "/ˈdʒenjuɪn/", "adj. 真正的；真诚的；名副其实的", "adjective", 2),
    ("gradual", "/ˈɡrædʒuəl/", "adj. 逐渐的；渐进的；缓慢的", "adjective", 2),
    ("harsh", "/hɑːrʃ/", "adj. 严厉的；苛刻的；恶劣的", "adjective", 2),
    ("humble", "/ˈhʌmbl/", "adj. 谦逊的；卑微的；简陋的", "adjective", 2),
    ("ideal", "/aɪˈdiːəl/", "adj. 理想的；完美的；观念的", "adjective", 2),
    ("ignorant", "/ˈɪɡnərənt/", "adj. 无知的；愚昧的；不了解的", "adjective", 3),
    ("immune", "/ɪˈmjuːn/", "adj. 免疫的；不受影响的；免除的", "adjective", 3),
    ("inevitable", "/ɪnˈevɪtəbl/", "adj. 不可避免的；必然的", "adjective", 3),
    ("inferior", "/ɪnˈfɪriər/", "adj. 劣等的；下级的；较差的", "adjective", 3),
    ("influential", "/ˌɪnfluˈenʃl/", "adj. 有影响力的；有势力的", "adjective", 3),
    ("inherent", "/ɪnˈhɪrənt/", "adj. 固有的；内在的；天生的", "adjective", 4),
    ("innocent", "/ˈɪnəsnt/", "adj. 无辜的；天真的；清白的", "adjective", 2),
    ("intense", "/ɪnˈtens/", "adj. 强烈的；紧张的；激烈的", "adjective", 2),
    ("internal", "/ɪnˈtɜːrnl/", "adj. 内部的；体内的；内在的", "adjective", 2),
    ("intimate", "/ˈɪntɪmət/", "adj. 亲密的；私人的；密切的", "adjective", 3),
    ("legitimate", "/lɪˈdʒɪtɪmət/", "adj. 合法的；正当的；合理的", "adjective", 4),
    ("liberal", "/ˈlɪbərəl/", "adj. 自由的；开明的；慷慨的", "adjective", 3),
    ("logical", "/ˈlɑːdʒɪkl/", "adj. 逻辑的；合理的；合乎逻辑的", "adjective", 2),
    ("loyal", "/ˈlɔɪəl/", "adj. 忠诚的；忠实的；忠心的", "adjective", 2),
    ("magnificent", "/mæɡˈnɪfɪsnt/", "adj. 壮丽的；宏伟的；极好的", "adjective", 3),
    ("massive", "/ˈmæsɪv/", "adj. 巨大的；大量的；大规模的", "adjective", 2),
    ("mature", "/məˈtʃʊr/", "adj. 成熟的；成年人的；完善的", "adjective", 2),
    ("mild", "/maɪld/", "adj. 温和的；轻微的；不严重的", "adjective", 2),
    ("moderate", "/ˈmɑːdərət/", "adj. 适度的；中等的；温和的", "adjective", 2),
    ("modest", "/ˈmɑːdɪst/", "adj. 谦虚的；适度的；朴素的", "adjective", 2),
    ("mutual", "/ˈmjuːtʃuəl/", "adj. 相互的；共同的；彼此的", "adjective", 2),
    ("negative", "/ˈneɡətɪv/", "adj. 消极的；否定的；负面的", "adjective", 2),
    ("numerous", "/ˈnuːmərəs/", "adj. 许多的；大量的；众多的", "adjective", 2),
    ("obvious", "/ˈɑːbviəs/", "adj. 明显的；显然的；显而易见的", "adjective", 2),
    ("offensive", "/əˈfensɪv/", "adj. 冒犯的；攻击性的；令人不快的", "adjective", 3),
    ("optimistic", "/ˌɑːptɪˈmɪstɪk/", "adj. 乐观的；乐观主义的", "adjective", 2),
    ("organic", "/ɔːrˈɡænɪk/", "adj. 有机的；器官的；组织的", "adjective", 2),
    ("outstanding", "/aʊtˈstændɪŋ/", "adj. 杰出的；突出的；未解决的", "adjective", 2),
    ("passionate", "/ˈpæʃənət/", "adj. 热情的；充满激情的；热烈的", "adjective", 2),
    ("peculiar", "/pɪˈkjuːliər/", "adj. 特有的；奇怪的；独特的", "adjective", 3),
    ("permanent", "/ˈpɜːrmənənt/", "adj. 永久的；持久的；不变的", "adjective", 2),
    ("pessimistic", "/ˌpesɪˈmɪstɪk/", "adj. 悲观的；悲观主义的", "adjective", 3),
    ("plausible", "/ˈplɔːzəbl/", "adj. 似乎合理的；貌似可信的", "adjective", 4),
    ("portable", "/ˈpɔːrtəbl/", "adj. 便携的；手提的；轻便的", "adjective", 2),
    ("potential", "/pəˈtenʃl/", "adj. 潜在的；可能的", "adjective", 2),
    ("precious", "/ˈpreʃəs/", "adj. 珍贵的；宝贵的；珍爱的", "adjective", 2),
    ("precise", "/prɪˈsaɪs/", "adj. 精确的；准确的；明确的", "adjective", 2),
    ("preliminary", "/prɪˈlɪmɪneri/", "adj. 初步的；预备的；开始的", "adjective", 3),
    ("prevailing", "/prɪˈveɪlɪŋ/", "adj. 盛行的；流行的；普遍的", "adjective", 3),
    ("primitive", "/ˈprɪmətɪv/", "adj. 原始的；早期的；简陋的", "adjective", 3),
    ("prior", "/ˈpraɪər/", "adj. 优先的；在前的；先前的", "adjective", 3),
    ("profound", "/prəˈfaʊnd/", "adj. 深刻的；深远的；渊博的", "adjective", 3),
    ("prominent", "/ˈprɑːmɪnənt/", "adj. 著名的；突出的；显著的", "adjective", 3),
    ("promising", "/ˈprɑːmɪsɪŋ/", "adj. 有前途的；有希望的", "adjective", 2),
    ("prompt", "/prɑːmpt/", "adj. 迅速的；及时的；敏捷的", "adjective", 3),
    ("prosperous", "/ˈprɑːspərəs/", "adj. 繁荣的；兴旺的；成功的", "adjective", 3),
    ("rational", "/ˈræʃnəl/", "adj. 理性的；合理的；理智的", "adjective", 3),
    ("rear", "/rɪr/", "adj. 后面的；后方的；背面的", "adjective", 2),
    ("reckless", "/ˈrekləs/", "adj. 鲁莽的；不顾后果的；粗心的", "adjective", 3),
    ("relevant", "/ˈreləvənt/", "adj. 相关的；切题的；有意义的", "adjective", 2),
    ("reliable", "/rɪˈlaɪəbl/", "adj. 可靠的；可信赖的；确实的", "adjective", 2),
    ("remarkable", "/rɪˈmɑːrkəbl/", "adj. 非凡的；显著的；引人注目的", "adjective", 2),
    ("remote", "/rɪˈmoʊt/", "adj. 遥远的；偏僻的；疏远的", "adjective", 2),
    ("resistant", "/rɪˈzɪstənt/", "adj. 抵抗的；反抗的；耐…的", "adjective", 3),
    ("respective", "/rɪˈspektɪv/", "adj. 各自的；分别的；相应的", "adjective", 3),
    ("revolutionary", "/ˌrevəˈluːʃəneri/", "adj. 革命的；革命性的；创新的", "adjective", 3),
    ("rigid", "/ˈrɪdʒɪd/", "adj. 严格的；僵硬的；死板的", "adjective", 3),
    ("rural", "/ˈrʊrəl/", "adj. 农村的；乡村的；田园的", "adjective", 2),
    ("sensible", "/ˈsensəbl/", "adj. 明智的；合理的；可感觉到的", "adjective", 2),
    ("sensitive", "/ˈsensətɪv/", "adj. 敏感的；灵敏的；易受影响的", "adjective", 2),
    ("severe", "/sɪˈvɪr/", "adj. 严重的；严厉的；剧烈的", "adjective", 2),
    ("shallow", "/ˈʃæloʊ/", "adj. 浅的；肤浅的；浅薄的", "adjective", 2),
    ("sincere", "/sɪnˈsɪr/", "adj. 真诚的；诚挚的；诚实的", "adjective", 2),
    ("skeptical", "/ˈskeptɪkl/", "adj. 怀疑的；持怀疑态度的", "adjective", 4),
    ("solemn", "/ˈsɑːləm/", "adj. 庄严的；严肃的；隆重的", "adjective", 3),
    ("sophisticated", "/səˈfɪstɪkeɪtɪd/", "adj. 复杂的；精密的；老练的", "adjective", 4),
    ("spontaneous", "/spɑːnˈteɪniəs/", "adj. 自发的；自然的；自动的", "adjective", 4),
    ("stable", "/ˈsteɪbl/", "adj. 稳定的；稳固的；沉稳的", "adjective", 2),
    ("static", "/ˈstætɪk/", "adj. 静态的；静止的；不变的", "adjective", 3),
    ("steady", "/ˈstedi/", "adj. 稳定的；平稳的；持续的", "adjective", 2),
    ("steep", "/stiːp/", "adj. 陡峭的；急剧的；过高的", "adjective", 2),
    ("stiff", "/stɪf/", "adj. 僵硬的；硬的；生硬的", "adjective", 2),
    ("subtle", "/ˈsʌtl/", "adj. 微妙的；精细的；敏锐的", "adjective", 4),
    ("sufficient", "/səˈfɪʃnt/", "adj. 足够的；充分的；充足的", "adjective", 2),
    ("superficial", "/ˌsuːpərˈfɪʃl/", "adj. 表面的；肤浅的；浅薄的", "adjective", 3),
    ("sustainable", "/səˈsteɪnəbl/", "adj. 可持续的；可维持的", "adjective", 3),
    ("temporary", "/ˈtempəreri/", "adj. 暂时的；临时的；短暂的", "adjective", 2),
    ("tender", "/ˈtendər/", "adj. 温柔的；嫩的；脆弱的", "adjective", 2),
    ("thorough", "/ˈθɜːroʊ/", "adj. 彻底的；全面的；仔细的", "adjective", 2),
    ("tough", "/tʌf/", "adj. 坚韧的；困难的；强硬的", "adjective", 2),
    ("tremendous", "/trɪˈmendəs/", "adj. 巨大的；极大的；惊人的", "adjective", 2),
    ("trivial", "/ˈtrɪviəl/", "adj. 琐碎的；不重要的；微不足道的", "adjective", 3),
    ("ultimate", "/ˈʌltɪmət/", "adj. 最终的；终极的；根本的", "adjective", 3),
    ("unanimous", "/juˈnænɪməs/", "adj. 一致的；全体一致的；无异议的", "adjective", 4),
    ("unique", "/juˈniːk/", "adj. 独特的；独一无二的；唯一的", "adjective", 2),
    ("universal", "/ˌjuːnɪˈvɜːrsl/", "adj. 普遍的；全体的；通用的", "adjective", 2),
    ("urban", "/ˈɜːrbən/", "adj. 城市的；都市的；城区的", "adjective", 2),
    ("urgent", "/ˈɜːrdʒənt/", "adj. 紧急的；急迫的；催促的", "adjective", 2),
    ("valid", "/ˈvælɪd/", "adj. 有效的；合理的；合法的", "adjective", 2),
    ("vast", "/væst/", "adj. 广阔的；巨大的；大量的", "adjective", 2),
    ("vigorous", "/ˈvɪɡərəs/", "adj. 有力的；精力充沛的；充满活力的", "adjective", 3),
    ("violent", "/ˈvaɪələnt/", "adj. 暴力的；猛烈的；剧烈的", "adjective", 2),
    ("visible", "/ˈvɪzəbl/", "adj. 可见的；明显的；看得见的", "adjective", 2),
    ("vital", "/ˈvaɪtl/", "adj. 至关重要的；生命的；充满活力的", "adjective", 2),
    ("vivid", "/ˈvɪvɪd/", "adj. 生动的；鲜明的；鲜艳的", "adjective", 2),
    ("voluntary", "/ˈvɑːlənteri/", "adj. 自愿的；志愿的；自发的", "adjective", 3),
    ("vulnerable", "/ˈvʌlnərəbl/", "adj. 易受伤的；脆弱的；易受攻击的", "adjective", 3),
    ("wealthy", "/ˈwelθi/", "adj. 富有的；丰富的；充裕的", "adjective", 2),
    ("widespread", "/ˈwaɪdspred/", "adj. 广泛的；普遍的；分布广的", "adjective", 2),
    ("worthwhile", "/ˌwɜːrθˈwaɪl/", "adj. 值得的；有价值的；合算的", "adjective", 2),

    # ── Adverbs (副词) ───────────────────────────────
    ("abruptly", "/əˈbrʌptli/", "adv. 突然地；唐突地；意外地", "adverb", 3),
    ("absolutely", "/ˈæbsəluːtli/", "adv. 绝对地；完全地；毫无疑问地", "adverb", 2),
    ("accordingly", "/əˈkɔːrdɪŋli/", "adv. 相应地；因此；于是", "adverb", 3),
    ("annually", "/ˈænjuəli/", "adv. 每年；一年一度地", "adverb", 2),
    ("apparently", "/əˈpærəntli/", "adv. 显然；表面上；似乎", "adverb", 3),
    ("approximately", "/əˈprɑːksɪmətli/", "adv. 大约；近似地；大概", "adverb", 2),
    ("barely", "/ˈberli/", "adv. 几乎不；仅仅；勉强", "adverb", 3),
    ("certainly", "/ˈsɜːrtnli/", "adv. 当然；必定；无疑地", "adverb", 2),
    ("comparatively", "/kəmˈpærətɪvli/", "adv. 相对地；比较地；相当地", "adverb", 3),
    ("consequently", "/ˈkɑːnsɪkwentli/", "adv. 因此；结果；所以", "adverb", 3),
    ("constantly", "/ˈkɑːnstəntli/", "adv. 不断地；经常地；持续地", "adverb", 2),
    ("currently", "/ˈkɜːrəntli/", "adv. 当前；目前；现在", "adverb", 2),
    ("deliberately", "/dɪˈlɪbərətli/", "adv. 故意地；慎重地；从容地", "adverb", 3),
    ("desperately", "/ˈdespərətli/", "adv. 绝望地；拼命地；极度地", "adverb", 3),
    ("dramatically", "/drəˈmætɪkli/", "adv. 戏剧性地；显著地；巨大地", "adverb", 3),
    ("efficiently", "/ɪˈfɪʃntli/", "adv. 高效地；有效地；能干地", "adverb", 2),
    ("enormously", "/ɪˈnɔːrməsli/", "adv. 巨大地；极大地；非常地", "adverb", 2),
    ("essentially", "/ɪˈsenʃəli/", "adv. 本质上；根本上；基本上", "adverb", 3),
    ("eventually", "/ɪˈventʃuəli/", "adv. 最终；终于；最后", "adverb", 2),
    ("excessively", "/ɪkˈsesɪvli/", "adv. 过度地；过分地；极度地", "adverb", 3),
    ("exclusively", "/ɪkˈskluːsɪvli/", "adv. 专有地；排外地；唯一地", "adverb", 3),
    ("frequently", "/ˈfriːkwəntli/", "adv. 频繁地；经常地；屡次地", "adverb", 2),
    ("genuinely", "/ˈdʒenjuɪnli/", "adv. 真正地；真诚地；名副其实地", "adverb", 2),
    ("gradually", "/ˈɡrædʒuəli/", "adv. 逐渐地；逐步地；渐进地", "adverb", 2),
    ("inevitably", "/ɪnˈevɪtəbli/", "adv. 不可避免地；必然地", "adverb", 3),
    ("invariably", "/ɪnˈveriəbli/", "adv. 总是；不变地；始终如一地", "adverb", 4),
    ("merely", "/ˈmɪrli/", "adv. 仅仅；只不过；只是", "adverb", 2),
    ("moderately", "/ˈmɑːdərətli/", "adv. 适度地；适中地；温和地", "adverb", 2),
    ("mutually", "/ˈmjuːtʃuəli/", "adv. 相互地；彼此地；共同地", "adverb", 3),
    ("namely", "/ˈneɪmli/", "adv. 即；也就是；换句话说", "adverb", 3),
    ("necessarily", "/ˌnesəˈserəli/", "adv. 必然地；必定地；必要地", "adverb", 3),
    ("nevertheless", "/ˌnevərðəˈles/", "adv. 然而；不过；尽管如此", "adverb", 3),
    ("obviously", "/ˈɑːbviəsli/", "adv. 显然；明显地；显而易见地", "adverb", 2),
    ("occasionally", "/əˈkeɪʒnəli/", "adv. 偶尔；间或；有时", "adverb", 2),
    ("particularly", "/pərˈtɪkjələrli/", "adv. 特别；尤其；格外", "adverb", 2),
    ("permanently", "/ˈpɜːrmənəntli/", "adv. 永久地；长期地；持久地", "adverb", 2),
    ("precisely", "/prɪˈsaɪsli/", "adv. 精确地；准确地；恰好", "adverb", 2),
    ("presumably", "/prɪˈzuːməbli/", "adv. 大概；可能；推测起来", "adverb", 3),
    ("profoundly", "/prəˈfaʊndli/", "adv. 深刻地；深深地；极度地", "adverb", 3),
    ("promptly", "/ˈprɑːmptli/", "adv. 迅速地；立即；及时地", "adverb", 2),
    ("readily", "/ˈredɪli/", "adv. 容易地；乐意地；迅速地", "adverb", 3),
    ("relatively", "/ˈrelətɪvli/", "adv. 相对地；比较地；相当", "adverb", 2),
    ("reluctantly", "/rɪˈlʌktəntli/", "adv. 不情愿地；勉强地", "adverb", 3),
    ("remarkably", "/rɪˈmɑːrkəbli/", "adv. 显著地；非凡地；引人注目地", "adverb", 3),
    ("respectively", "/rɪˈspektɪvli/", "adv. 分别地；各自地；依次地", "adverb", 3),
    ("scarcely", "/ˈskersli/", "adv. 几乎不；简直不；刚刚", "adverb", 3),
    ("significantly", "/sɪɡˈnɪfɪkəntli/", "adv. 显著地；重要地；意味深长地", "adverb", 3),
    ("slightly", "/ˈslaɪtli/", "adv. 稍微；轻微地；略微", "adverb", 2),
    ("somewhat", "/ˈsʌmwʌt/", "adv. 有点；稍微；几分", "adverb", 2),
    ("specifically", "/spəˈsɪfɪkli/", "adv. 特别地；明确地；具体地", "adverb", 3),
    ("steadily", "/ˈstedɪli/", "adv. 稳定地；平稳地；持续地", "adverb", 2),
    ("subsequently", "/ˈsʌbsɪkwəntli/", "adv. 随后；后来；接着", "adverb", 3),
    ("substantially", "/səbˈstænʃəli/", "adv. 实质上；大体上；相当多地", "adverb", 4),
    ("sufficiently", "/səˈfɪʃntli/", "adv. 足够地；充分地；充足地", "adverb", 2),
    ("temporarily", "/ˈtempərerəli/", "adv. 暂时地；临时地", "adverb", 2),
    ("thoroughly", "/ˈθɜːrəli/", "adv. 彻底地；完全地；仔细地", "adverb", 2),
    ("ultimately", "/ˈʌltɪmətli/", "adv. 最终；最后；根本上", "adverb", 2),
    ("unanimously", "/juˈnænɪməsli/", "adv. 一致地；全体一致地", "adverb", 4),
    ("undoubtedly", "/ʌnˈdaʊtɪdli/", "adv. 无疑地；毫无疑问地；肯定地", "adverb", 3),
    ("unfortunately", "/ʌnˈfɔːrtʃənətli/", "adv. 不幸地；遗憾地；可惜地", "adverb", 2),
    ("vigorously", "/ˈvɪɡərəsli/", "adv. 有力地；精力充沛地；强劲地", "adverb", 3),
    ("virtually", "/ˈvɜːrtʃuəli/", "adv. 几乎；实际上；虚拟地", "adverb", 3),

    # ── Phrases (短语) ───────────────────────────────
    ("a series of", "/ə ˈsɪriːz əv/", "一系列；一连串", "A series of experiments were conducted.", "进行了一系列实验。", "phrase", 2),
    ("account for", "/əˈkaʊnt fɔːr/", "解释；说明；占（比例）", "This accounts for 30% of the total.", "这占总数的30%。", "phrase", 3),
    ("adapt to", "/əˈdæpt tu/", "适应；适合", "It takes time to adapt to a new environment.", "适应新环境需要时间。", "phrase", 2),
    ("apply for", "/əˈplaɪ fɔːr/", "申请；请求", "She decided to apply for the scholarship.", "她决定申请奖学金。", "phrase", 2),
    ("as a result", "/æz ə rɪˈzʌlt/", "结果；因此", "As a result, the project was delayed.", "结果，项目被推迟了。", "phrase", 2),
    ("as well as", "/æz wel æz/", "也；以及；和…一样好", "She speaks French as well as English.", "她说法语也说英语。", "phrase", 2),
    ("at risk", "/æt rɪsk/", "处于危险中；有风险", "Many species are at risk of extinction.", "许多物种面临灭绝的危险。", "phrase", 2),
    ("be accustomed to", "/bi əˈkʌstəmd tu/", "习惯于；适应", "He is accustomed to getting up early.", "他习惯早起。", "phrase", 3),
    ("be bound to", "/bi baʊnd tu/", "必然；一定会；有义务", "You are bound to succeed if you persist.", "如果你坚持，你一定会成功。", "phrase", 3),
    ("be capable of", "/bi ˈkeɪpəbl əv/", "有能力做；能够", "She is capable of handling complex tasks.", "她有能力处理复杂任务。", "phrase", 2),
    ("break down", "/breɪk daʊn/", "分解；出故障；崩溃", "The car broke down on the highway.", "车在高速公路上抛锚了。", "phrase", 2),
    ("bring about", "/brɪŋ əˈbaʊt/", "引起；导致；带来", "Technology has brought about great changes.", "技术带来了巨大的变化。", "phrase", 3),
    ("call for", "/kɔːl fɔːr/", "需要；呼吁；要求", "This situation calls for immediate action.", "这种情况需要立即采取行动。", "phrase", 2),
    ("carry out", "/ˈkæri aʊt/", "执行；实施；完成", "The team carried out a series of tests.", "团队进行了一系列测试。", "phrase", 2),
    ("come up with", "/kʌm ʌp wɪð/", "想出；提出；赶上", "She came up with a brilliant idea.", "她想出了一个绝妙的主意。", "phrase", 2),
    ("contribute to", "/kənˈtrɪbjuːt tu/", "贡献；有助于；导致", "Exercise contributes to better health.", "运动有助于改善健康。", "phrase", 2),
    ("cope with", "/koʊp wɪð/", "应对；处理；对付", "We must learn to cope with stress.", "我们必须学会应对压力。", "phrase", 2),
    ("deal with", "/diːl wɪð/", "处理；应对；涉及", "The book deals with environmental issues.", "这本书涉及环境问题。", "phrase", 2),
    ("depend on", "/dɪˈpend ɑːn/", "依赖；取决于；信赖", "Success depends on hard work and dedication.", "成功取决于勤奋和投入。", "phrase", 2),
    ("derive from", "/dɪˈraɪv frʌm/", "来源于；从…中获得", "Many English words derive from Latin.", "许多英语单词来源于拉丁语。", "phrase", 3),
    ("devote to", "/dɪˈvoʊt tu/", "致力于；奉献给；专注于", "She devoted her life to education.", "她把一生奉献给了教育。", "phrase", 2),
    ("due to", "/duː tu/", "由于；因为；归因于", "The flight was cancelled due to bad weather.", "航班因恶劣天气取消了。", "phrase", 2),
    ("engage in", "/ɪnˈɡeɪdʒ ɪn/", "从事；参与；忙于", "Students should engage in extracurricular activities.", "学生应该参与课外活动。", "phrase", 3),
    ("even if", "/ˈiːvn ɪf/", "即使；尽管；纵然", "Even if it rains, we will go ahead.", "即使下雨，我们也会继续。", "phrase", 2),
    ("figure out", "/ˈfɪɡjər aʊt/", "弄清楚；计算出；理解", "I can't figure out how to solve this problem.", "我想不出如何解决这个问题。", "phrase", 2),
    ("focus on", "/ˈfoʊkəs ɑːn/", "专注于；集中于；聚焦", "We should focus on the most important tasks.", "我们应该专注于最重要的任务。", "phrase", 2),
    ("get rid of", "/ɡet rɪd əv/", "摆脱；除去；丢弃", "It's time to get rid of old habits.", "是时候改掉旧习惯了。", "phrase", 2),
    ("give rise to", "/ɡɪv raɪz tu/", "引起；导致；产生", "The new policy gave rise to much debate.", "新政策引起了很多争论。", "phrase", 3),
    ("in addition to", "/ɪn əˈdɪʃn tu/", "除…之外；另外；加之", "In addition to English, she speaks Japanese.", "除了英语，她还会说日语。", "phrase", 2),
    ("in contrast", "/ɪn ˈkɑːntræst/", "相比之下；与此相反", "In contrast, the second option is cheaper.", "相比之下，第二个选项更便宜。", "phrase", 3),
    ("in favor of", "/ɪn ˈfeɪvər əv/", "支持；赞成；有利于", "Most people voted in favor of the proposal.", "大多数人投票支持该提案。", "phrase", 2),
    ("in other words", "/ɪn ˈʌðər wɜːrdz/", "换句话说；也就是说", "In other words, we need to start over.", "换句话说，我们需要重新开始。", "phrase", 2),
    ("in response to", "/ɪn rɪˈspɑːns tu/", "作为回应；响应；回答", "The law was changed in response to public demand.", "法律应公众要求而修改。", "phrase", 3),
    ("in terms of", "/ɪn tɜːrmz əv/", "就…而言；在…方面", "In terms of quality, this product is the best.", "就质量而言，这个产品是最好的。", "phrase", 2),
    ("lead to", "/liːd tu/", "导致；通向；引起", "Smoking can lead to serious health problems.", "吸烟会导致严重的健康问题。", "phrase", 2),
    ("make sense", "/meɪk sens/", "有意义；有道理；讲得通", "His explanation doesn't make sense.", "他的解释说不通。", "phrase", 2),
    ("no matter", "/noʊ ˈmætər/", "无论；不管", "No matter what happens, don't give up.", "无论发生什么，都不要放弃。", "phrase", 2),
    ("on behalf of", "/ɑːn bɪˈhæf əv/", "代表；为了…的利益", "I'm speaking on behalf of the entire team.", "我代表整个团队发言。", "phrase", 3),
    ("on the contrary", "/ɑːn ðə ˈkɑːntreri/", "相反；正相反；反之", "On the contrary, the results were excellent.", "相反，结果非常好。", "phrase", 3),
    ("on the other hand", "/ɑːn ði ˈʌðər hænd/", "另一方面；反过来说", "On the other hand, there are some risks.", "另一方面，也存在一些风险。", "phrase", 2),
    ("pay attention to", "/peɪ əˈtenʃn tu/", "注意；关注；重视", "Please pay attention to the safety instructions.", "请注意安全须知。", "phrase", 2),
    ("point out", "/pɔɪnt aʊt/", "指出；指明；提示", "She pointed out several errors in the report.", "她指出了报告中的几个错误。", "phrase", 2),
    ("put forward", "/pʊt ˈfɔːrwərd/", "提出；建议；推荐", "He put forward an interesting proposal.", "他提出了一个有趣的建议。", "phrase", 3),
    ("rather than", "/ˈræðər ðæn/", "而不是；宁可…也不", "I prefer to walk rather than take the bus.", "我宁愿走路也不坐公交。", "phrase", 2),
    ("refer to", "/rɪˈfɜːr tu/", "提到；参考；涉及", "The term refers to a specific type of plant.", "这个术语指的是一种特定的植物。", "phrase", 2),
    ("regardless of", "/rɪˈɡɑːrdləs əv/", "不管；不顾；无论", "The event will go ahead regardless of the weather.", "无论天气如何，活动都会进行。", "phrase", 3),
    ("rely on", "/rɪˈlaɪ ɑːn/", "依赖；依靠；信赖", "We rely on technology in our daily lives.", "我们在日常生活中依赖技术。", "phrase", 2),
    ("result in", "/rɪˈzʌlt ɪn/", "导致；结果是；造成", "The accident resulted in serious injuries.", "事故导致了严重伤害。", "phrase", 2),
    ("set up", "/set ʌp/", "建立；设立；安排", "They set up a new company last year.", "他们去年成立了一家新公司。", "phrase", 2),
    ("take advantage of", "/teɪk ədˈvæntɪdʒ əv/", "利用；占…的便宜", "We should take advantage of this opportunity.", "我们应该利用这个机会。", "phrase", 2),
    ("take into account", "/teɪk ˈɪntu əˈkaʊnt/", "考虑；顾及；斟酌", "You should take his opinion into account.", "你应该考虑他的意见。", "phrase", 3),
    ("take over", "/teɪk ˈoʊvər/", "接管；接收；取代", "The company was taken over by a larger firm.", "这家公司被一家更大的公司接管了。", "phrase", 2),
    ("turn out", "/tɜːrn aʊt/", "结果是；证明是；生产", "It turned out to be a great success.", "结果证明这是一个巨大的成功。", "phrase", 2),
    ("with regard to", "/wɪð rɪˈɡɑːrd tu/", "关于；至于；就…而言", "With regard to your question, here is my answer.", "关于你的问题，这是我的回答。", "phrase", 3),
]


# ============================================================
# Template-based example generation
# ============================================================

VERB_EXAMPLES = [
    ("The company decided to {word} the plan.", "公司决定{word_cn}该计划。"),
    ("Scientists are working to {word} the phenomenon.", "科学家正在努力{word_cn}这一现象。"),
    ("We need to {word} this issue immediately.", "我们需要立即{word_cn}这个问题。"),
    ("It is important to {word} new skills.", "{word_cn}新技能很重要。"),
    ("The government should {word} more resources to education.", "政府应该向教育{word_cn}更多资源。"),
    ("She managed to {word} all her goals.", "她成功{word_cn}了所有目标。"),
    ("They {word} the importance of teamwork.", "他们{word_cn}了团队合作的重要性。"),
    ("The report {word}s the need for change.", "该报告{word_cn}了变革的必要性。"),
]

NOUN_EXAMPLES = [
    ("{word} is essential for success.", "{word_cn}对成功至关重要。"),
    ("The {word} of this project cannot be underestimated.", "这个项目的{word_cn}不可低估。"),
    ("We discussed the {word} in detail.", "我们详细讨论了{word_cn}。"),
    ("A good {word} is the foundation of learning.", "良好的{word_cn}是学习的基础。"),
    ("The {word} has improved significantly.", "{word_cn}有了显著改善。"),
    ("Education plays a key role in developing {word}.", "教育在培养{word_cn}方面起着关键作用。"),
]

ADJ_EXAMPLES = [
    ("This is a {word} factor in the decision.", "这是决策中的一个{word_cn}因素。"),
    ("The results were {word} and encouraging.", "结果是{word_cn}且令人鼓舞的。"),
    ("A {word} approach is needed to solve this problem.", "解决这个问题需要一种{word_cn}的方法。"),
    ("The {word} difference between the two samples is clear.", "两个样本之间的{word_cn}差异很明显。"),
    ("It is {word} to check the data before publishing.", "在发布之前检查数据是{word_cn}的。"),
]

ADV_EXAMPLES = [
    ("The situation has {word} improved.", "情况{word_cn}改善了。"),
    ("{word}, the project was completed on time.", "{word_cn}，项目按时完成了。"),
    ("She {word} explained her point of view.", "她{word_cn}阐述了自己的观点。"),
    ("The number of users has grown {word}.", "用户数量{word_cn}增长了。"),
]


def get_cn_head(word_def):
    """Extract Chinese definition without the POS prefix."""
    parts = word_def.split(" ", 1)
    return parts[1] if len(parts) > 1 else word_def


def clean_cn(cn_def):
    """Get a clean Chinese definition for use in example sentences."""
    # Remove the POS prefix like "v. ", "n. ", etc.
    parts = cn_def.split(" ", 1)
    cn = parts[1] if len(parts) > 1 else cn_def
    # Take the first meaning (before first semicolon)
    cn = cn.split("；")[0].split("；")[0]
    return cn


def generate_example(word, word_def, category):
    """Generate appropriate example based on category."""
    cn_head = clean_cn(word_def)
    templates = {
        "verb": VERB_EXAMPLES,
        "noun": NOUN_EXAMPLES,
        "adjective": ADJ_EXAMPLES,
        "adverb": ADV_EXAMPLES,
    }.get(category, VERB_EXAMPLES)

    # Pick a template deterministically based on word
    idx = hash(word) % len(templates)
    en_tpl, cn_tpl = templates[idx]

    en_sentence = en_tpl.replace("{word}", word)
    # For adverb, capitalize the first letter if it starts the sentence
    if category == "adverb" and en_sentence.startswith(word):
        en_sentence = word.capitalize() + en_sentence[len(word):]

    cn_sentence = cn_tpl.replace("{word_cn}", cn_head)

    return en_sentence, cn_sentence


def main():
    items = []

    for entry in WORDS:
        if len(entry) == 7:
            # Phrase with explicit examples
            word, pronunciation, definition, example, example_trans, category, difficulty = entry
        else:
            word, pronunciation, definition, category, difficulty = entry
            example, example_trans = generate_example(word, definition, category)

        items.append({
            "word": word,
            "pronunciation": pronunciation,
            "definition": definition,
            "example": example,
            "exampleTranslation": example_trans,
            "category": category,
            "difficulty": difficulty,
        })

    # Assign IDs
    cat_counters = {}
    for item in items:
        cat = item["category"]
        prefix_map = {"verb": "v", "noun": "n", "adjective": "adj", "adverb": "adv", "phrase": "phrase"}
        prefix = prefix_map.get(cat, cat)
        cat_counters[prefix] = cat_counters.get(prefix, 0) + 1
        item["id"] = f"{prefix}-{cat_counters[prefix]:04d}"

    # Build output
    output = {
        "type": "vocabulary",
        "title": "CET-4 核心词汇",
        "description": "包含CET-4核心词汇，涵盖动词、名词、形容词、副词和常用短语，每条记录包含音标、释义、例句和翻译",
        "items": items,
    }

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data", "vocabulary-bank.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    # Stats
    cats = {}
    for item in items:
        c = item["category"]
        cats[c] = cats.get(c, 0) + 1
    print(f"Generated {len(items)} vocabulary items")
    print(f"Categories: {cats}")
    print(f"Output: {out_path}")


if __name__ == "__main__":
    main()